UPPER_CHARS = 'ABCDEFGHIJKLMNOPKRSTUVWXYZ'

LOWER_CHARS = 'abcdefghijklmnopkrstuvwxyz'

NUMBER_CHARS = '123456789'

SPECIAL_CHARS = '-_'

RAND_CHARS = UPPER_CHARS + LOWER_CHARS + NUMBER_CHARS + SPECIAL_CHARS